import { Inter } from 'next/font/google'
import Header from './components/Header/page'
import Footer from './components/Footer/page'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Speed iRose Online',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-back-color-main min-h-screen`}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
